### PR TITLE
Add code issue templates and put install instructions in README.md

### PR DESCRIPTION
**Pull request by 0rdinal**

### CODE REVIEW

**Comment by 0rdinal** [comment]
@cokwa Don't suppose you could make a me a contributer so I can help you with issues etc?

**Comment by RyuTheRyu** [comment]
i would also like to help with issues.

**Comment by cokwa** [comment]
Sure, I'll see what I can do later. It's a late time here.

**Comment by cokwa** [comment]
@Genetical I think I invited you to be a collaborator just now.

**Comment by 0rdinal** [comment]
@cokwa You did, thank you.

**Comment by 0rdinal** [comment]
@cokwa Is there a better way that we can talk? Like through discord? Talking on PR's isn't the greatest

**Comment by cokwa** [comment]
Hyunsung Go#6214

Can you add me as a friend with this? I'm not used to Discord.

**Comment by 0rdinal** [comment]
Added.

**Pull request merged**
